{
 "title": "EVA ICS Overview",
 "tags": [ "eva" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "eva",
    "label": "Connection",
    "query": "bohemiaautomation-evaics-datasource"
   }
  ]
 },
 "panels": [
  {
   "title": "Node info",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "targets": [
    { "queryText": "test" }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "queryText": "bus::eva.core::core.sysinfo" }
   ]
  },
  {
   "title": "Cloud status",
   "type": "table",
   "gridPos": { "h": 13, "w": 16, "x": 8, "y": 5 },
   "targets": [
    { "queryText": "bus::eva.core::node.list" }
   ]
  },
  {
   "title": "HMI sessions",
   "type": "table",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "queryText": "bus::eva.hmi.default::session.list"
    }
   ]
  }
 ]
}